name: PyCosm checks and tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9] # Matching Docker container

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Check code formatting with Black
      run: pipenv run make black-check
    - name: Check code style with Flake8
      run: pipenv run make flake
    - name: Check static type with Mypy
      run: pipenv run make mypy
    - name: Run unit tests
      run: pipenv run make test
    - name: Check security with Bandit
      run: pipenv run make bandit
    - name: Check safety
      run: pipenv run make safety
    - name: Check imports order with Isort
      run: pipenv run make isort
    - name: Unused code check with Vulture
      run: pipenv run make vulture
    - name: Code check with PyLint
      run: pipenv run make pylint
